-- SQL para crear las tablas necesarias para la app de fitness
-- Ejecutar en Supabase SQL editor o en psql conectado a la base de datos

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar not null,
  email varchar not null unique,
  created_at timestamptz default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name varchar not null,
  category varchar not null,
  description text,
  level varchar,
  created_at timestamptz default now()
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  name varchar not null,
  duration int not null,
  user_id bigint not null references public.users(id) on delete restrict,
  created_at timestamptz default now()
);

create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete restrict,
  sets int,
  reps int
);
